# Generated by Django 2.1 on 2018-10-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='paradign',
            new_name='paradigm',
        ),
    ]
